#Requires -Version 7.0
<#
.SYNOPSIS
    Phase 5 — Global .gitignore

.DESCRIPTION
    Script Name : phase_05_gitignore.ps1
    Purpose     : Write ~/.gitignore_global covering Windows OS files, VS Code
                  artifacts, JetBrains IDEs, common temp files, secrets,
                  Python build artifacts, and Node modules. Verifies that
                  core.excludesFile in ~/.gitconfig points to this file.
    Phase       : 5 of 12
    Exit Criteria: ~/.gitignore_global exists and
                   git config --global core.excludesFile returns a valid path.

.NOTES
    Run with: pwsh -File scripts\phase_05_gitignore.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

function Write-Info    { param([string]$Msg) Write-Host "  [INFO] $Msg"    -ForegroundColor Cyan    }
function Write-Pass    { param([string]$Msg) Write-Host "  [PASS] $Msg"    -ForegroundColor Green   }
function Write-Warn    { param([string]$Msg) Write-Host "  [WARN] $Msg"    -ForegroundColor Yellow  }
function Write-Fail    { param([string]$Msg) Write-Host "  [FAIL] $Msg"    -ForegroundColor Red     }
function Write-Section { param([string]$Msg) Write-Host "`n==> $Msg"       -ForegroundColor White   }

function Abort {
    param([string]$Msg)
    Write-Fail $Msg
    Write-Host "`nScript aborted. Fix the issue above and re-run Phase 5.`n" -ForegroundColor Red
    exit 1
}

# ---------------------------------------------------------------------------
# Section header
# ---------------------------------------------------------------------------

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  Phase 5 — Global .gitignore"            -ForegroundColor Cyan
Write-Host "  Repo root: $RepoRoot"                   -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

$gitignorePath = Join-Path $HOME '.gitignore_global'
$Results = [ordered]@{}

# ---------------------------------------------------------------------------
# Step 1 — Write ~/.gitignore_global
# ---------------------------------------------------------------------------

Write-Section "Step 1 — Write ~/.gitignore_global"

# Note: The $RECYCLE.BIN line uses a PS escape. In the file it must appear
# literally as $RECYCLE.BIN/ — we use a here-string with single quotes to
# prevent variable expansion, then write via Set-Content.

$gitignoreContent = @'
# =============================================================================
# ~/.gitignore_global — Global gitignore
# Generated by phase_05_gitignore.ps1
# =============================================================================

# -----------------------------------------------------------------------------
# Windows OS files
# -----------------------------------------------------------------------------
Thumbs.db
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/
*.lnk

# -----------------------------------------------------------------------------
# VS Code (keep extensions.json tracked; ignore user-specific files)
# -----------------------------------------------------------------------------
.vscode/settings.json
.vscode/*.code-workspace
.vscode/launch.json
.vscode/.history/

# -----------------------------------------------------------------------------
# JetBrains IDEs
# -----------------------------------------------------------------------------
.idea/
*.iml

# -----------------------------------------------------------------------------
# General temp / editor artifacts
# -----------------------------------------------------------------------------
*.log
*.tmp
*.bak
*.swp
*.swo
.DS_Store

# -----------------------------------------------------------------------------
# Environment files / secrets — never commit these
# -----------------------------------------------------------------------------
.env
.env.*
!.env.example
*.pem
*.key
secrets.*
credentials.*

# -----------------------------------------------------------------------------
# Python
# -----------------------------------------------------------------------------
.venv/
__pycache__/
*.pyc
*.pyo
*.pyd
.pytest_cache/
*.egg-info/
dist/
build/
.coverage
htmlcov/

# -----------------------------------------------------------------------------
# Node / JavaScript
# -----------------------------------------------------------------------------
node_modules/
npm-debug.log*

# -----------------------------------------------------------------------------
# Archives (avoid accidentally committing large binary blobs)
# -----------------------------------------------------------------------------
*.zip
*.tar.gz
*.rar
'@

try {
    Set-Content -Path $gitignorePath -Value $gitignoreContent -Encoding UTF8
    Write-Pass "Written: $gitignorePath"
    $Results['~/.gitignore_global Written'] = 'PASS'
} catch {
    Abort "Failed to write $gitignorePath`: $_"
}

# ---------------------------------------------------------------------------
# Step 2 — Verify core.excludesFile in gitconfig
# ---------------------------------------------------------------------------

Write-Section "Step 2 — Verify core.excludesFile in ~/.gitconfig"

try {
    $excludesFile = git config --global core.excludesFile 2>&1
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($excludesFile)) {
        Write-Warn "core.excludesFile is not set in ~/.gitconfig. Setting it now..."
        git config --global core.excludesFile "$HOME/.gitignore_global"
        Write-Pass "Set core.excludesFile = $HOME/.gitignore_global"
        $Results['core.excludesFile Set'] = 'PASS'
    } else {
        $excludesFile = $excludesFile.Trim()
        Write-Pass "core.excludesFile is already set: $excludesFile"

        # Resolve the path to verify it points to our file
        # git stores it with forward slashes and may use ~ shorthand
        $resolvedPath = $excludesFile -replace '^~', $HOME -replace '/', '\'
        if (Test-Path $resolvedPath) {
            Write-Pass "Resolved path exists on disk: $resolvedPath"
            $Results['core.excludesFile Set'] = 'PASS'
        } elseif ($excludesFile -match 'gitignore_global') {
            Write-Pass "Path contains 'gitignore_global' — assumed correct"
            $Results['core.excludesFile Set'] = 'PASS'
        } else {
            Write-Warn "core.excludesFile points to '$excludesFile' which does not match ~/.gitignore_global"
            Write-Warn "Updating to $HOME/.gitignore_global"
            git config --global core.excludesFile "$HOME/.gitignore_global"
            $Results['core.excludesFile Set'] = 'PASS (updated)'
        }
    }
} catch {
    Write-Warn "Could not check or set core.excludesFile: $_"
    Write-Info "Manual fix: git config --global core.excludesFile `"~/.gitignore_global`""
    $Results['core.excludesFile Set'] = 'WARN'
}

# ---------------------------------------------------------------------------
# Step 3 — Show the file contents for confirmation
# ---------------------------------------------------------------------------

Write-Section "Step 3 — File contents (preview)"

Write-Info "First 20 lines of ~/.gitignore_global:"
Write-Host ""
$lines = Get-Content $gitignorePath | Select-Object -First 20
foreach ($line in $lines) {
    Write-Host "  $line" -ForegroundColor Cyan
}
Write-Host "  ..." -ForegroundColor Cyan
Write-Host ""
$lineCount = (Get-Content $gitignorePath).Count
Write-Info "Total lines: $lineCount"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  Phase 5 — Summary"                       -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

$colW = 35
Write-Host ("{0,-$colW} {1}" -f 'Step', 'Status') -ForegroundColor White
Write-Host ("{0,-$colW} {1}" -f ('-' * ($colW - 1)), '------') -ForegroundColor White

$anyFail = $false
foreach ($kv in $Results.GetEnumerator()) {
    $color = switch -Wildcard ($kv.Value) {
        'PASS*' { 'Green'  }
        'FAIL'  { 'Red'    }
        'WARN'  { 'Yellow' }
        default { 'White'  }
    }
    Write-Host ("{0,-$colW} {1}" -f $kv.Key, $kv.Value) -ForegroundColor $color
    if ($kv.Value -eq 'FAIL') { $anyFail = $true }
}

Write-Host ""
if ($anyFail) {
    Write-Fail "One or more steps failed. Review the output above and fix before running Phase 6."
    exit 1
} else {
    Write-Pass "Global gitignore is configured. Proceed to Phase 6 (hooks and secret scanning)."
    exit 0
}
